services:
  - type: web
    name: nuvora-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: flask db upgrade && gunicorn --bind 0.0.0.0:$PORT app:app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: nuvora-db
          property: connectionString
      - key: OPENAI_API_KEY
        sync: false
      - key: FLASK_APP
        value: app:app
    pythonVersion: 3.10
