services:
  - type: web
    name: nuvora-api
    runtime: python
    buildCommand: ""
    startCommand: "gunicorn app:app"
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: OPENAI_API_KEY
        sync: false

